//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeDeLi1.Dbase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHangChoXacNhan
    {
        public string MaDonHangTam { get; set; }
        public string LoaiDon { get; set; }
        public string DiaChiLayHang { get; set; }
        public Nullable<System.DateTime> ThoiGianLayHang { get; set; }
        public string DiaChiGiaoHang { get; set; }
        public Nullable<System.DateTime> ThoiGianGiaoHang { get; set; }
        public Nullable<double> KhoiLuong { get; set; }
        public string MaNguoiDung { get; set; }
        public string MaPhuongTien { get; set; }
        public string MaNhaXe { get; set; }
        public string TrangThai { get; set; }
    }
}
